import fetch from 'node-fetch' 

const respuestas = {
  'hola': { text: 'Hola 👋, ¡qué gusto saludarte!' },
  'adiós': { text: '¡Hasta luego! Que tengas un gran día 🌟' },
  'qué bueno': { text: 'Me alegra que pienses así 😊' },
  'qué tal están': { text: '¡Estamos bien, gracias por preguntar! ¿Y tú?' },
  'buenos días': { text: '¡Buenos días! Que tengas un excelente día ☀️' },
  'buenas tardes': { text: '¡Buenas tardes! Espero que tu día esté genial 🌇' },
  'buenas noches': { text: '¡Buenas noches! Que descanses y sueñes bonito 🌙' },
  'gracias': { text: '¡De nada! Para eso estoy 🤖' },
  'cómo estás': { text: '¡Estoy bien, gracias! ¿En qué te puedo ayudar?' },
  'qué haces': { text: 'Estoy aquí respondiendo tus mensajes 🤖' },
  'buen trabajo': { text: '¡Gracias! Me esfuerzo mucho para ayudarte 😊' },
  'feliz cumpleaños': { text: '¡Feliz cumpleaños! 🎉 Que tengas un día maravilloso' },
  'buen finde': { text: '¡Feliz fin de semana! Descansa y disfruta mucho 🏖️' },
  'lo siento': { text: 'No hay problema, ¡todo está bien! 🤗' },
  'estoy bien': { text: 'Me alegra saberlo 😊 ¿En qué puedo ayudarte?' },
  'qué pasa': { text: 'Nada fuera de lo normal, aquí atento para ayudarte 👍' },
  'saludos': { text: '¡Saludos para ti también! 👋' },
  'buenas': { text: '¡Buenas! ¿Cómo puedo ayudarte?' },
  'gracias por todo': { text: '¡Es un placer ayudarte siempre! 😊' },
  'nos vemos': { text: '¡Nos vemos pronto! Cuídate mucho 🤗' },
  'buenas noches a todos': { text: '¡Buenas noches! Que todos descansen bien 🌙' },
  'cómo va todo': { text: 'Todo va genial, gracias por preguntar 😄' },
  'qué tal todo': { text: 'Todo está en orden por aquí 👍' },
  'hola qué tal': { text: '¡Hola! Todo bien, ¿y tú?' },

  // 🔥 100 frases nuevas
  'jajaja': { text: '😂😂 qué risa!' },
  'xd': { text: 'XDDD 🤣' },
  'ok': { text: '👌 Dale, entendido' },
  'vale': { text: '¡Perfecto! 👍' },
  'alv': { text: '😱 En serio? Qué fuerte' },
  'wtf': { text: '😳 Qué rayos!' },
  'bro': { text: 'Qué onda bro ✌️' },
  'amigo': { text: 'Siempre a la orden, amigo 🤝' },
  'tqm': { text: 'Yo también te quiero mucho 💖' },
  'te amo': { text: 'Aww, yo también te amo 💕' },
  'like': { text: 'Dale like 👍' },
  'arre': { text: '¡Arre pues! 😎' },
  'uff': { text: 'Ufff 🔥🔥🔥' },
  'no mames': { text: '😂😂 jajaja literal!' },
  'enserio': { text: 'Sí, en serio 😏' },
  'wtf bro': { text: '😳 Qué fue eso bro?' },
  'aja': { text: 'Ajá, te escucho 👂' },
  'ya': { text: '¡Ya quedó! ✅' },
  'wtf xd': { text: 'Eso fue rarísimo pero gracioso 😂' },
  'like si': { text: 'Like si estás de acuerdo 👍' },
  'mmm': { text: 'Mmmm 🤔 interesante' },
  'okey': { text: 'Okey dokey ✌️' },
  'qué onda': { text: '¡Todo chill! 😎' },
  'estás bien': { text: 'Sí, todo bien gracias 🙌' },
  'wtf jajaja': { text: 'JAJAJA qué random 😂' },
  'qué rollo': { text: '¡Todo tranqui! 🤙' },
  'f': { text: 'F en el chat 😔' },
  'rip': { text: 'Descansa en paz 😢' },
  'wow': { text: 'Wow 😲 impresionante!' },
  'genial': { text: '¡Eso está genial! 😎' },
  'cool': { text: 'Cool 😎👌' },
  'brooo': { text: 'Brooooo 🔥🔥🔥' },
  'ya llegué': { text: '¡Bienvenido/a! 👋' },
  'vamo': { text: '¡Vamo arriba! 🚀' },
  'vamos': { text: '¡Sí se puede! 💪' },
  'toy': { text: 'Aquí toy 🙋‍♂️' },
  'estoy aburrido': { text: 'Hagamos algo divertido 😏' },
  'qué aburrido': { text: 'Sí, está aburrido 😴' },
  'me estreso': { text: 'Respira, todo va a estar bien 😌' },
  'jaja': { text: 'Jajaja 😂' },
  'ajaja': { text: 'Ajajaja 🤣' },
  'nojoda': { text: '¡Qué locura! 😅' },
  'wtf man': { text: 'Man, eso no tiene sentido 😳' },
  'brother': { text: 'Mi brother ✌️' },
  'hermano': { text: 'Hermanooo 💪' },
  'siii': { text: 'Siii 🔥🔥🔥' },
  'nooo': { text: 'Nooooo 😱' },
  'ayuda': { text: 'Claro, ¿en qué te ayudo? 🛟' },
  'porfa': { text: 'Claro que sí 🙌' },
  'wtfff': { text: '😳😳 Qué locuraaaa' },
  'omg': { text: 'Oh my god 😱' },
  'que pro': { text: '¡Eres un pro! 🎮🔥' },
  'pro': { text: 'Pro player 💯' },
  'bot': { text: 'Aquí estoy 🤖' },
  'gracias bot': { text: 'De nada 👾' },
  'amo este grupo': { text: 'Este grupo es el mejor 💖' },
  'somos los mejores': { text: 'Obvio 💯🔥' },
  'equipo': { text: '¡Vamos equipo! 💪' },
  'ganamos': { text: 'GANAMOS 🎉🎉🎉' },
  'perdimos': { text: 'Perdimos 😢 pero seguimos fuertes' },
  'otra vez': { text: 'Vamos otra vez 🔁' },
  'cállate': { text: 'Jajaja ya me callo 🤐' },
  'calla': { text: 'Ok, shhh 🤫' },
  'mentira': { text: '¿Mentira? No lo creo 😏' },
  'es verdad': { text: '¡Claro que sí! ✅' },
  'literal': { text: 'Literal 😅' },
  'ya fue': { text: 'Ya fue, ni modo 🤷' },
  'me voy': { text: 'Ok, cuídate 👋' },
  'ya vuelvo': { text: 'Dale, aquí te espero ⏳' },
  'tengo sueño': { text: 'Ve a dormir 😴' },
  'qué rico': { text: 'Ufff delicioso 😋' },
  'qué asco': { text: 'Puaj 🤢' },
  'de locos': { text: 'Literal de locos 🔥' },
  'neta': { text: 'Sí neta 😎' },
  'pues sí': { text: 'Exacto 👍' },
  'ya dije': { text: 'Ok entendido 🙌' },
  'obvio': { text: 'Obvio 😏' },
  'obvio que sí': { text: 'Obvio que sí 🔥' },
  'no sé': { text: 'Ni idea 🤔' },
  'qué fue eso': { text: 'No sé pero estuvo raro 😅' },
  'qué': { text: '¿Qué pasó? 👀' },
  'ya entendí': { text: 'Perfecto, me alegra 😄' },
  'wtf loco': { text: 'Jajaja loco 🤣' },
  'tranqui': { text: 'Tranqui, todo bien 🙌' },
  'relax': { text: 'Relax bro 😎' },
  'me muero': { text: 'Jajajajaja 😂😂' },
  'estoy vivo': { text: 'Y seguimos vivos 🙌' },
  'soy yo': { text: '¡Hola tú! 👋' },
  'quién': { text: 'Soy yo 🤖' },
  'es broma': { text: 'Ah, ok 😂' },
  'jajsjajs': { text: 'Jajajaja qué loco 🤣' },
  'bye': { text: 'Bye bye 👋' },
  'hasta mañana': { text: 'Hasta mañana 🌙' },
  'hasta luego': { text: 'Hasta luego 👋' },
  'mañana': { text: 'Mañana será otro día ☀️' },
  'hoy': { text: 'Hoy toca disfrutar 😎' },
  'ahora': { text: 'Es ahora o nunca 🚀' },
  'hahaha': { text: 'Hahaha 😂😂' },
  'jsjs': { text: 'Jsjsjs 🤣🤣' },
  'ajaj': { text: 'Ajajajaja 😂' },
  'jeje': { text: 'Jejeje 😏' },
  'jojo': { text: 'Jojojo 😈' },
  'wtf jajaj': { text: 'Qué random jajaj 😂' },
  'xddd': { text: 'XDDDDDD 🤣' },
  'zzz': { text: 'Zzz 😴 dormido' },
  'me muero de risa': { text: 'JAJAJA yo igual 😂😂' },
  'lol': { text: 'LOL 🤣🤣' },
  'lmao': { text: 'LMAO 😆🔥' },
  'haha': { text: 'Hahahah 🤭' },
  'eh': { text: 'Ehhhh 👀' },
  'no': { text: 'si 😼'},
  'si': { text: 'no 😼'},
  'verdad': { text: 'Mentira 😂'},
  'mentira': { text: 'Es verdad 🤣'},
  'na': { text: 'Naaa 😏' },
  'ya no': { text: 'Ok, entendido 🙌' },
  'ya dije que no': { text: 'Ok tranquilo ✌️' },
  'ya entendiste': { text: 'Sí, entendido ✅' },
  'obvio que no': { text: 'Obvio que no 😅' },
  'seguro': { text: 'Segurísimo 🔒' },
  'tal vez': { text: 'Tal vez 🤔' },
  'quizás': { text: 'Quizás 👀' },
  'capaz': { text: 'Capaz 🤷' },
  'imposible': { text: 'Nada es imposible 🚀' },
  'posible': { text: 'Sí es posible 💯' },
  'creo': { text: 'Yo también lo creo 🤔' },
  'me parece': { text: 'Me parece bien 👌' },
  'está bien': { text: 'Perfecto ✅' },
  'no importa': { text: 'Está bien, no importa ✌️' },
  'ya fue xd': { text: 'Ya fueee 😂' },
  'dale': { text: 'Dale 🔥' },
  'dale pues': { text: 'Dale pues 😎' },
  'eso': { text: '¡Eso! 🔥' },
  'exacto': { text: 'Exacto 👌' },
  'cierto': { text: 'Muy cierto 👍' },
  'en efecto': { text: 'En efecto 🤝' },
  'obviamente': { text: 'Obviamente 😏' },
  'real': { text: 'Eso es real 💯' },
  'muy real': { text: 'Demasiado real 🔥' },
  'qué loco': { text: 'Loco de verdad 😅' },
  'loco': { text: 'Loco jajaja 🤯' },
  'random': { text: 'Qué random 🤣' },
  'cringe': { text: 'Cringe 😬' },
  'based': { text: 'Based 😎' },
  'chill': { text: 'Todo chill 😌' },
  'tranquilo': { text: 'Tranqui 🙌' },
  'no te preocupes': { text: 'Todo bien 😉' },
  'gracias amigo': { text: 'De nada amigo 🙌' },
  'gracias bro': { text: 'De nada bro 💯' },
  'gracias hermano': { text: 'Siempre hermano 🤝' },
  'gracias crack': { text: 'De nada crack 🔥' },
  'crack': { text: 'Tremendo crack 💪' },
  'ídolo': { text: 'Eres un ídolo 🔥' },
  'maquinola': { text: 'Eres una máquina 💯' },
  'profe': { text: 'Dígame profe 👨‍🏫' },
  'wtf amigo': { text: 'Qué fue eso amigo 😂' },
  'ya entendí todo': { text: 'Excelente 🙌' },
  'listo': { text: 'Listo ✅' },
  'preparado': { text: 'Preparado 🔥' },
  'vámonos': { text: 'Vámonos 🚀' },
  'nos vamos': { text: 'Nos vamos pues 👋' },
  'estoy triste': { text: 'Ánimo, todo mejora 💖' },
  'me siento mal': { text: 'Todo va a mejorar, confía ✨' },
  'ando feliz': { text: 'Me alegra mucho 😄' },
  'ando sad': { text: 'Tranquilo, pasa pronto 😢' },
  'ando chill': { text: 'Todo relax 😌' },
  'ando motivado': { text: '¡Así se habla! 💪' },
  'ando cansado': { text: 'Descansa un poco 😴' },
  'ando ocupado': { text: 'Ok, luego hablamos ⏳' },
  'ando libre': { text: 'Perfecto, aprovecha 🕒' },
  'tengo hambre': { text: 'Vamos a comer 🍕' },
  'qué comemos': { text: 'Lo que quieras 🍔🍟' },
  'tengo sed': { text: 'Agua siempre 💧' },
  'salud': { text: '¡Salud! 🥂' },
  'brindis': { text: 'Brindemos 🥳' },
  'felicidades': { text: '¡Felicidades! 🎉' },
  'felicitaciones': { text: 'Muchas felicidades 👏' },
  'buen provecho': { text: '¡Gracias, igualmente! 🍽️' },
  'con gusto': { text: 'Siempre con gusto 😊' },
  'a huevo': { text: '¡A huevo! 🔥' },
  'simón': { text: 'Simón bro ✌️' },
  'ya estuvo': { text: 'Ya estuvo ✨' },
  'me estafaron': { text: 'Qué mal 😔' },
  'no importa xd': { text: 'Tranqui, ya pasó 🤷' },
  'soy feliz': { text: 'Qué bonito 💖' },
  'no soy feliz': { text: 'Tranquilo, todo cambiará 🙏' },
  'te extraño': { text: 'Yo también te extraño 💕' },
  'extraño': { text: 'Extrañando 😢' },
  'bye bye': { text: 'Bye bye 👋' },
  'chao': { text: 'Chaooo 👋' },
  'nos vemos luego': { text: 'Nos vemos ✌️' },
  'nos vemos mañana': { text: 'Hasta mañana 🌙' },
  'nos vemos bro': { text: 'Dale bro 👊' },
  'ya nos vamos': { text: 'Sí, ya nos vamos 🚪' },
  'ya llegamos': { text: 'Perfecto 👌' },
  'de una': { text: 'De una 🔥' },
  'al toque': { text: 'Al toque bro ⚡' },
  'ah bueno': { text: 'Ah bueno 😏' },
  'qué dices': { text: 'Digo que sí 😎' },
  'dime': { text: 'Aquí estoy, dime 👂' },
  'ya dime': { text: 'Ok, dime de una vez 🙌' },
  'no digas': { text: 'Ok no digo nada 🤐' },
  'cállese': { text: 'Jajaja ya me callo 🤫' }
}


let handler = async (m, { conn }) => {
  if (!m.text) return
  const texto = m.text.toLowerCase().trim()
 if (m.fromMe) return
  let chat = global.db.data.chats[m.chat]
  if (!chat) {
    global.db.data.chats[m.chat] = { autoresponder2: false, isBanned: false }
    chat = global.db.data.chats[m.chat]
  }

  if (!chat.autoresponder2) return      
  if (chat.isBanned) return            


  let key = Object.keys(respuestas).find(k => k === texto)
  if (!key) return

  let r = respuestas[key]
const res = await fetch(`${kirito}/media/images/87411733_k.jpg`);
  const thumb2 = Buffer.from(await res.arrayBuffer());
const userJid = m.sender;

  const fkontak = {
    key: { fromMe: false, participant: userJid },
    message: {
      imageMessage: {
        mimetype: 'image/jpeg',
        caption: '𝗥𝗘𝗦𝗣𝗨𝗘𝗦𝗧𝗔 > 𝗕𝗢𝗧',
        jpegThumbnail: thumb2
      }
    }
  };

    await conn.sendMessage(m.chat, { text: r.text }, { quoted: fkontak })
  }


handler.customPrefix = new RegExp(`^(${Object.keys(respuestas).map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})$`, 'i')
handler.command = new RegExp
export default handler